### ISSUE TITLE
Add sheet lock/unlock methods

### ISSUE THREAD

**Issue by theycallmeswift** [FlatFilers/flatfile-node#22]
<img src="https://a.slack-edge.com/80588/marketing/img/meta/favicon-32.png" height="16" width="16" alt="Slack logo" /> [#triage-eng-support thread](https://flatfile.slack.com/archives/C05MXFTD04A/p1703090503793369)

Currently neither of the lock or unlock endpoints have corresponding methods.

 - https://reference.flatfile.com/api-reference/sheets/lock-a-sheet
 - https://reference.flatfile.com/api-reference/sheets/unlock-a-sheet

**Comment by theycallmeswift** [comment]
@dsinghvi looks like the method is there after upgrading! However, it appears there is something wrong with the type definition.

I'm getting the following Eslint error for the lock/unlock calls in the sample below, which I don't get for the other sheet.X methods:

```
Unsafe call of an `any` typed value.eslint[@typescript-eslint/no-unsafe-call](https://typescript-eslint.io/rules/no-unsafe-call)
```


```typescript
const id = "foo";
const { data: sheet } = await api.sheets.get(id);

await api.sheets.lockSheet(sheet.id);
await api.sheets.unlockSheet(sheet.id);
```

**Comment by damonbanks** [comment]
@dsinghvi I have a PR to fix the lack of types in the Platform workbook service (which is what these endpoints use). But the codegen didnt change at all. I am not sure that this will fix the sdk problem.

**Comment by damonbanks** [comment]
@theycallmeswift I pulled the most recent Flatfile SDK and I am not seeing the above errors. Can you please confirm that this is fixed on your side as well? Thank you.

**Comment by theycallmeswift** [comment]
Yes, upgrading worked, thanks!

**Comment by damonbanks** [comment]
@theycallmeswift Glad that worked!
