### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by chen-annie** [FlatFilers/flatfile-node#23]
I don't see a LICENSE file or other indication of what the license of the `@flatfile/api` package is - could you add one? If there isn't a license I can't use the package.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3ussr0)

**Comment by dsinghvi** [comment]
Yes we can! @ashleygmulligan2 will a MIT License work for Flatfile?

**Comment by ashleygmulligan2** [comment]
Yes, that works!

**Comment by chen-annie** [comment]
Do you have a timeline for when the license will be added?
