### ISSUE TITLE
Flatfile listener type expects void instead of Promise<void>

### ISSUE THREAD

**Issue by theycallmeswift** [FlatFilers/flatfile-node#31]
This issue is with the `EventCallback` and `EventHandler.use` type definitions . The current definitions are as follows:

```typescript
export type EventCallback = (evt: FlatfileEvent) => void;

use(fn: (handler: this) => void): this;
```

However, we should be able to accept either a function that returns void or `Promise<void>`  per [this example](https://github.com/FlatFilers/demo-agent/blob/main/src/demos/simple.ts#L17) _(and logically since we don’t actually care about the return value)_.

```typescript
export type EventCallback = (evt: FlatfileEvent) => void | Promise<void>;

use(fn: (handler: this) => Promise<void>): this;
```

Additional context here: [https://flatfile-developers.slack.com/archives/C05B557MD61/p1701318501796279](https://flatfile-developers.slack.com/archives/C05B557MD61/p1701318501796279)

**Comment by dboskovic** [comment]
Hey @theycallmeswift - can you upgrade [`@flatfile/listener`](https://www.npmjs.com/package/@flatfile/listener) to `^0.3.18` - we just released a fix for this.

**Comment by theycallmeswift** [comment]
Resolved, thanks!
